steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    env: [ 'REPO=$PROJECT_ID' ]
    args:
      - '--destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '--build-arg=REPO'
      - '--cache=true'
      - '--cache-ttl=168h'
      - '--use-new-run'
      - '--registry-mirror=$_GCR_HOSTNAME'
    id: Build
    timeout: 2400s
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
timeout: 3600s
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - $_SERVICE_NAME
  - $COMMIT_SHA
  - $SHORT_SHA
  - $REPO_NAME
  - $_DEPLOY_REGION
